name: NPM with NodeJS and react-scripts

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js v${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # based on example from: https://github.com/pmndrs/website/blob/main/.github/workflows/pages.yml
    # and https://github.com/actions/starter-workflows/blob/main/pages/nextjs.yml
    - name: configure_github_pages
      id: configurepages
      uses: actions/configure-pages@v5

    - name: build
      run: |
        echo "Starting GitHub build.."
        cd game
        npm ci
        npm run clean
        npm run build
        # npm run test # TODO
        echo "GitHub build done\x21"

    - uses: actions/upload-pages-artifact@v3
      with:
        path: ./game/build

    # - name: deployTwo
    #   uses: peaceiris/actions-gh-pages@v4
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./game/build

  # based on example from: https://github.com/pmndrs/website/blob/main/.github/workflows/pages.yml
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # permissions for peaceiris/...
    # permissions:
    #   contents: write
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: deployment_to_github_pages
        id: deployment
        uses: actions/deploy-pages@v4

# EOF


